CREATE TABLE MEMBER
( SEQ NUMBER(8) PRIMARY KEY
, ID VARCHAR2(150)
, PASSWORD VARCHAR2(200)
, NAME VARCHAR2(150)
, AGE NUMBER(8)
, GENDER CHAR(1)
, IMG_PATH VARCHAR2(1000)
, IMG_NAME VARCHAR2(1000)
);

DROP TABLE MEMBER PURGE;

SELECT * FROM MEMBER;

INSERT INTO MEMBER(SEQ, ID, PASSWORD, NAME, AGE, GENDER, IMG_PATH, IMG_NAME) VALUES (1, 'chunkind', 'wnstjd', '김준성', 29, 'M', '', '');

DELETE FROM MEMBER;

